version: "3.8"

services:
  webserver:
    build:
      context: .
      dockerfile: bin/webserver/Dockerfile
    ports:
      - "${HOST_MACHINE_HTTP_PORT}:80"
    volumes:
      - ./webroot:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-available
      - ./logs/apache2:/var/log/apache2
    environment:
      - DB_SERVER=${DB_SERVER}
     
  db:
    image: ${DB_SERVER}
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}